### PR TITLE
use `@codemirror/language-data` for more modes

### PR DESCRIPTION
**Pull request by jaked**
Instead of explicitly listing language modes, use `@codemirror/language-data` to get a bunch of predefined ones.

I am not too sure what Next.js does with the [dynamic imports](https://github.com/codemirror/language-data/blob/main/src/language-data.ts)—I hope it splits the code and only loads modes you ask for. The additional languages are about 800K.

(This seems pretty non-essential and I don't mind abandoning it if people think it's a bad idea.)

### CODE REVIEW

**Comment by jaked** [comment]
Vite at least seems to load only modes you ask for.

**Review by Wattenberger — APPROVED** [review]
image

**Review by mattrothenberg — APPROVED** [review]
You could test this locally if you're concerned about `next` doing the wrong thing with those dynamic imports!

**Comment by jaked** [comment]
> You could test this locally if you're concerned about `next` doing the wrong thing with those dynamic imports!

Is there a way to test in `blocks` without publishing `blocks-examples`?

**Pull request merged**
