### PR TITLE
feat: remove tailwind hook call, bump utils

### PR DESCRIPTION
**Pull request by mattrothenberg**
- Bump `utils` to latest
- Remove any instances of `useTailwindCdn` hook
- Add hard-coded reference to `twind` shim

### CODE REVIEW

**Review by Wattenberger — APPROVED** [review]
yiss!

**Comment by jaked** [comment]
for the uninitiated: what's the difference between Tailwind CDN and `twind/shim`, and between these vs. using Tailwind at build time?

**Comment by mattrothenberg** [comment]
@jaked Conceptually nothing. `twind` is a small compiler that converts utility classes to Tailwind styles. Both `twind` and the Tailwind team have scripts via CDN you can plop on to your website. Anecdotally, the former is much faster than the latter.

Before, we have a `useTailwindCdn` hook that users manually had to  call in order to inject the Tailwind CDN into their page, and I realized this was stupid. We _know_ the Tailwind CDN url, so why not just stick that in the head tag of every block. So I deprecated the hook altogether, and moved us over to `twind` in order to hopefully get a speed gain.

LMK if that makes sense!

**Comment by jaked** [comment]
cool thanks!

**Pull request merged**
